language: java
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      # Use newer Java (1.8.0_31 is too old)
      - oracle-java8-installer
cache:
  directories:
    - $HOME/.m2
before_cache:
  - rm -rf $HOME/.m2/repository/org/marsik

